"""Generate the synthetic sample alert dataset.

The sample must *demonstrate* the product: it carries a deliberate, high-contrast
``region + hour`` pattern -- a near-silent daytime trough, a busy night and a
steep evening ramp, and a wide spread between busy and quiet regions -- plus
light noise. That makes the risk scores demonstrative and lets the historical
baseline beat a constant base-rate predictor under rolling-origin validation
instead of flagging "low confidence" on a toy.

It is synthetic and does NOT represent real alert data; the output is marked with
a ``#`` banner line saying so. Run from the repo root:

    python scripts/generate_sample_data.py

Output is deterministic (fixed seed) so the committed CSV diffs cleanly.
"""

from __future__ import annotations

import csv
import random
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

SEED = 20260624
WEEKS = 8
START = date(2026, 4, 6)  # Monday; Apr-May 2026 is entirely Kyiv summer time (+03:00)
KYIV = timezone(timedelta(hours=3))
OUT = Path(__file__).resolve().parents[1] / "data" / "sample_alerts.csv"

# A '#' banner written as the first CSV line marks the file as synthetic. The
# loader skips '#' lines, so this is ignored by parsing but unmistakable to
# anyone who opens the file.
BANNER = (
    "# SYNTHETIC SAMPLE DATA - generated by scripts/generate_sample_data.py; "
    "NOT real air-raid alerts. For demonstration only. See data/README.md."
)

# Diurnal alert-start propensity by local hour. Deliberately high-contrast so
# the risk scores are demonstrative: a near-silent daytime trough (07-15) and a
# busy night plus a steep, monotonic evening ramp (18 < 19 < 20 < 21 < 22 < 23).
HOUR_WEIGHT = {
    0: 0.55, 1: 0.52, 2: 0.48, 3: 0.40, 4: 0.30,
    5: 0.12, 6: 0.04, 7: 0.02, 8: 0.015, 9: 0.012, 10: 0.012,
    11: 0.012, 12: 0.012, 13: 0.014, 14: 0.018, 15: 0.025,
    16: 0.05, 17: 0.10,
    18: 0.20, 19: 0.30, 20: 0.40, 21: 0.48, 22: 0.52, 23: 0.55,
}

# Region overall intensity (a second, stable signal dimension on top of hour).
# A wide spread so busy regions (Kharkiv, Kyiv) read clearly riskier than quiet
# ones (Ivano-Frankivsk, Lviv).
REGION_INTENSITY = {
    "Kharkiv": 1.25,
    "Kyiv": 1.05,
    "Odesa": 0.85,
    "Zhytomyr": 0.55,
    "Rivne": 0.45,
    "Ivano-Frankivsk": 0.28,
    "Lviv": 0.16,
}


def _alert_probability(region: str, hour: int) -> float:
    return min(0.85, HOUR_WEIGHT[hour] * REGION_INTENSITY[region])


def generate_rows() -> list[dict[str, str]]:
    rng = random.Random(SEED)
    rows: list[dict[str, str]] = []
    for day_offset in range(WEEKS * 7):
        day = START + timedelta(days=day_offset)
        for region in REGION_INTENSITY:
            for hour in range(24):
                if rng.random() >= _alert_probability(region, hour):
                    continue
                start = datetime(day.year, day.month, day.day, hour, rng.randint(0, 59), tzinfo=KYIV)
                end = start + timedelta(minutes=rng.randint(30, 120))
                rows.append(
                    {
                        "region": region,
                        "started_at": start.isoformat(),
                        "ended_at": end.isoformat(),
                    }
                )
    rows.sort(key=lambda row: (row["region"], row["started_at"]))
    return rows


def main() -> None:
    rows = generate_rows()
    with OUT.open("w", newline="", encoding="utf-8") as handle:
        handle.write(BANNER + "\n")
        writer = csv.DictWriter(handle, fieldnames=["region", "started_at", "ended_at"])
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} synthetic alert events to {OUT}")


if __name__ == "__main__":
    main()
